### ISSUE TITLE
Can we block these requests?

### ISSUE THREAD

**Issue by javaDeveloperKid** [berthubert/googerteller#11]
Can we block these or this repo's functionality is just informational?

**Comment by jonas-w** [comment]
You could archieve this with a firewall and add all these subnets listed in goog-prefixes.txt to a blocklist for outgoing traffic.

But this will break stuff on the internet

**Comment by douglaz** [comment]
A script for this would be very interesting

**Comment by douglaz** [comment]
> But this will break stuff on the internet

Only blocking google isn't enough, but I guess that if you add Amazon and Microsoft service, then probably yes

**Comment by jonas-w** [comment]
@javaDeveloperKid it will break your browsing experience. Sadly most websites rely on google or google servers.

**Comment by berthubert** [comment]
Hi - you can block Google easily enough, and a surprising amount of the web continues to work. The biggest issue is that ReCaptcha no longer works. Blocking however is not the focus of this tool, so I am closing this issue here.
