### ISSUE TITLE
Step-by-step instructions for newbs?

### ISSUE THREAD

**Issue by Gilbog** [berthubert/googerteller#18]
Hi, as a newbie I'm having a lot of fun with Linux (Mint, in my case) command line and I'm learning fast.
But your instructions in the README.md are incomprehensible to me. 
Any chance you'd post step-by-step commands I'd have to run to get your cool program to work?
Thanks for thinking of those still learning to become Google- & Microsoft-independent

**Comment by sq1000000** [comment]
I agree, the instructions on how to install are way too complicated. This the most I could reduce it down to:

```
sudo apt install cmake gcc git tcpdump libpcaudio-dev ipset
git clone https://github.com/berthubert/googerteller.git
cd googerteller/
cmake .
make
sudo ./ipset-setup.sh
sudo tcpdump -i nflog:20 -ln | ./teller
```
For whatever reason, that works on debian, but not on my arch build, so if you run arch, try:
```
sudo pacman -S cmake gcc git tcpdump pcaudiolib ipset net-tools 
git clone https://github.com/berthubert/googerteller.git
cd googerteller/
cmake .
make
sudo tcpdump -n -l dst net $(route -n | grep 'UG[ \t]' | awk '{print $2}')/32 $(for a in $(cat goog-prefixes.txt); do echo or dst net $a; done)  |  ./teller
```

**Comment by Gilbog** [comment]
Thanks sq100000!
I tried the first set of instructions, but I'm stuck on `cmake .` which returns: 
```
Make Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

```
Seems I need a compiler, is that something I can also just download for free? I'm on Linux Mint 21.

**Comment by spycrowsoft** [comment]
This how you can install some of the stuff you might need on a Debian machine.
It'll probably work on mint as well as that's Debian based, but I cannot give you any guarantees.

```
apt -y install build-essential debhelper devscripts cmake cmake-doc cmake-extras tcpdump libpcaudio0 libpcaudio-dev
```

After this, you should be able to follow the readme.

**Comment by Gilbog** [comment]
Great, it worked! Thanks for your help, spycrowsoft!
